### ISSUE TITLE
Allow for range track styling with only one active/highlighted mark text

### ISSUE THREAD

**Issue by joeyfigaro** [react-component/slider#219]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/2z1E231f3P27283H1n3a/Image%202017-02-16%20at%2010.12.53%20AM.png?X-CloudApp-Visitor-Id=37226ef4a83c849204ef6a1efa01836b&v=85916b95)

^ Would like a way to add specific styles for the currently selected active step's mark text so that I can have something like this:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1A1M162M1z2h143u3I31/Image%202017-02-16%20at%2010.13.55%20AM.png?X-CloudApp-Visitor-Id=37226ef4a83c849204ef6a1efa01836b&v=f83172d2)

**Comment by joeyfigaro** [comment]
Ended up solving this with css selectors, but it'd still be nice to have a dedicated class for the currently selected mark's text. 

```scss
.rc-slider {
	&-dot {
		width: 9px;
		height: 9px;

		background-color: color(tertiary);
		border: none;

		&-active ~ .rc-slider-dot {
			background-color: color(ashVariant);
		}
	}
}
```
