### ISSUE TITLE
Indication for focus

### ISSUE THREAD

**Issue by Vishal1419** [react-component/slider#672]
I have checked the documentation and other issues, but unfortunately I cannot find any way to add box-shadow or change color of the handle when there is a focus on the handle.
I am using slider in single handle mode.

Is there any way to achieve this?

**Comment by B-l-u-e-b-e-r-r-y** [comment]
I try to override the global style, it works:
```css
.rc-slider-handle-dragging {
    box-shadow: 0 0 0 5px red !important;
}
```
