### ISSUE TITLE
Feature Request: Theming with `css-vars`

### ISSUE THREAD

**Issue by KasperAndersson** [react-component/slider#819]
Ex:
```css
.rc-slider-rail {
  position: absolute;
  width: 100%;
  height: 4px;
  background-color: var(--rc-slider-rail-background, #e9e9e9);
  border-radius: 6px;
}
```

```css
:root {
  --rc-slider-rail-background: #e9e9e9;
  --rc-slider-track-background: #abe2fb;

  --rc-slider-handle-background: #fff;
  --rc-slider-handle-border-color: #96dbfa;
  --rc-slider-handle-dragging-background: #fff;
  --rc-slider-handle-dragging-border-color: #57c5f7;
  --rc-slider-handle-dragging-box-shadow-color: #96dbfa;
  ...,
}
```
